### ISSUE TITLE
Mumax view

### ISSUE THREAD

**Issue by MathieuMoalic** [ubermag/discretisedfield#156]
Hi there,
Have you considered integrating [mumax-view](https://github.com/JeroenMulkers/mumax-view) as a tool to visualize 3D fields ?
Compared to k3d, it is faster as it is compiled to wasm and has better shaders out of the box.
I'm not sure if it's possible to embed it as a notebook widget in a similar way to k3d. Also it would require a few changes to be called through python. 
I doubt this would be an easy task but k3d can be insanely slow even on top-end workstations ( single-threaded js can only go so far ). I also think mumax-view is a beautifully written software that deserves more attention and it might shine as part of the Ubermag framework.

**Comment by lang-m** [comment]
@MathieuMoalic How big (e.g. how much cells) are your magnetisation fields?

**Comment by MathieuMoalic** [comment]
well, it really depends. It can go from 512 x 512 x 1 to 4096 x 256 x 5. I also visualize time resolved data so you can multiply that by another factor.
Of course I step the cells and don't plot all millions of arrows ...

**Comment by lang-m** [comment]
To find potential performance bottlenecks we would need to know an approximate number of arrows that you are plotting.

**Comment by MathieuMoalic** [comment]
I appreciate that you are trying to help me in this particular case but k3d's issue tracker would be more appropriate for performance improvements. I'm wondering more about Ubermag and mumax-view's potential integration.

**Comment by fangohr** [comment]
Thank you for the suggestion. A quick first brain storm suggests that we will not be able to push a mumax-view integration at this point. There are multiple aspects coming together, including the mumax-view code not appearing to be actively maintained, it being targeted quite closely to mumax-based micromagnetism (many features of the relevant `discretisedfield` module are not limited to micromagnetics and can thus serve a wider community), and also the lacking (as far as I can see) integration with Jupyter notebooks. 

I agree that k3d is not the most versatile tool - we have some ideas how to improve the situation, but should focus first on making more basic things work within ubermag.

Please keep reporting issues: even though we may not be able to react to them, it is still useful to learn about user experiences.

**Comment by fangohr** [comment]
I think there may have been an issue that mumax-view only reads the ovf files generated by mumax (not those by oommf). If I recall this correctly, it is probably because of an [extra space](https://github.com/ubermag/discretisedfield/blob/master/discretisedfield/field.py#L3321) or something like that: we had noticed this when teaching discretised field to read the ovf file from mumax. Even if correct, this can be fixed of course - it is just a matter of time invested.

Do get in touch if you make progress: if the obstacles are removed, and we could integrate additional tools with relatively little effort, that becomes more realistic and feasible.
