### ISSUE TITLE
Repeat the code on the official website, but the scale of the drawing is different

### ISSUE THREAD

**Issue by hhh123hhh123** [ubermag/discretisedfield#221]
[](https://ubermag.github.io/getting-started/notebooks/magnetisation-field.html#)
<img width="598" alt="12" src="https://user-images.githubusercontent.com/116707163/204137600-5ca210e9-cf07-4fe9-85ff-02bd7e4e1c5c.png">
<img width="232" alt="13" src="https://user-images.githubusercontent.com/116707163/204137602-79253db4-de1f-4061-9781-b8e9a4407179.png">

**Comment by hhh123hhh123** [comment]
The first one is my result, and the next one is the result on the official website

**Comment by hhh123hhh123** [comment]
Does anyone know where I am setting it wrong?

**Comment by lang-m** [comment]
Hi @hhh123hhh123 
your plot is the (desired) new behaviour because the aspect ratio is correct. (We know that the labels easily tend to overlap. However, as we think that these kinds of plots are mainly used for quick checks we think that the correct aspect ratio is more important that axis labels.)

You can still get the old behaviour with
```python
region.mpl(box_aspect=(1, 1, 1))
```
(https://ubermag.github.io/api/_autosummary/discretisedfield.plotting.MplRegion.html)

Where on the website did you see the other plot?

**Comment by hhh123hhh123** [comment]
@lang-m Thank you very much. your method is very useful
